server:
  bind: ""
  port: 3000
mcp_servers: []
pipeline:
  steps:
    - type: extractTags
      embedder:
        model: nomic-embed-text:latest
        base_url: http://10.0.10.12:11434/v1
    - type: fork
      fork:
        - type: reduceTools
        - type: retrieveKnowledge
    - type: llm
      llm:
        model: myaniu/qwen2.5-1m:14b
        base_url: http://10.0.10.12:11434/v1

