server:
  bind: 0.0.0.0
  port: 3000
mcp_servers: []
llm:
  model: gpt-3.5-turbo
  temperature: 0.7
  max_tokens: 1000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
pipeline:
  steps:
    - type: llm
      llm:
        model: gpt-3.5-turbo
        base_url: http://10.0.10.12:11434/v1
        temperature: 0.7
        max_tokens: 1000
        top_p: 1.0
        frequency_penalty: 0.0
        presence_penalty: 0.0